//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgreementLog
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Time { get; set; }
        public int agreementID { get; set; }
        public int userID { get; set; }
        public string notes { get; set; }
    
        public virtual Agreement Agreement { get; set; }
        public virtual User User { get; set; }
    }
}
