//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Agreement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agreement()
        {
            this.Requests = new HashSet<Request>();
        }

        public int ID { get; set; }

        [DisplayName("Partner")]
        public Nullable<int> partnerID { get; set; }

        [DisplayName("Service")]
        public int serviceID { get; set; }

        [DisplayName("Label")]
        public string label { get; set; }

        [DataType(DataType.MultilineText)]
        [DisplayName("Description")]
        public string description { get; set; }

        [DisplayName("Is active")]
        public bool isActive { get; set; }

        [DataType(DataType.MultilineText)]
        [DisplayName("Confirmation Text")]
        public string messageTemplate { get; set; }

        [DataType(DataType.MultilineText)]
        [DisplayName("Agent instructions")]
        public string agentInstructions { get; set; }

        [DataType(DataType.MultilineText)]
        [DisplayName("Cancellation policy")]
        public string cancellationPolicy { get; set; }

        [DisplayName("Needs approval")]
        public bool needsApproval { get; set; }

        [DisplayName("Price")]
        public Nullable<decimal> price { get; set; }

        [DisplayName("Commission type")]
        public Nullable<int> commissionType { get; set; }

        //[RegularExpression(@"^\d+\.\d{0,2}$")]
        //[Range(0, 1)]
        [DisplayName("Commission value")]
        //[RegularExpression("[^.[0-9,.]*$]", ErrorMessage = "UPRN must be numeric")]
        public Nullable<decimal> commissionValue { get; set; }



        [DisplayName("Override price?")]
        public Nullable<bool> Override1 { get; set; }

        [DisplayName("Agent payment")]
        public Nullable<decimal> PaymentAgent { get; set; }

        [DisplayName("Email to customer")]
        public string EmailToCustomer { get; set; }

        [DisplayName("Type of payment to agent")]
        public Nullable<int> PaymentAgentType { get; set; }

        [DisplayName("Type of price")]
        public Nullable<int> priceType { get; set; }

        [DisplayName("Commission type")]
        public Nullable<int> TypeCommission { get; set; }

        [DisplayName("is confirmed?")]
        public Nullable<bool> isConfirmed { get; set; }

        public virtual Service Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
        public virtual Partner Partner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgreementLog> AgreementLogs { get; set; }
        public virtual DynamicField DynamicField { get; set; }
        public virtual DynamicFieldAlternative DynamicFieldAlternative { get; set; }
        public virtual DynamicFieldAlternative DynamicFieldAlternative1 { get; set; }
        public virtual DynamicFieldAlternative DynamicFieldAlternative2 { get; set; }
    }
}
