//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynamicFieldMl
    {
        public string languageID { get; set; }
        public string label { get; set; }
        public int dynamicfieldID { get; set; }
    
        public virtual DynamicField DynamicField { get; set; }
        public virtual Language Language { get; set; }
    }
}
