//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityAccess
{
    using System;
    using System.Collections.Generic;

    public partial class ErrorLog
    {
        public int ID { get; set; }
        public int User { get; set; }
        public Nullable<System.DateTime> errorDate { get; set; }
        public Nullable<System.TimeSpan> errorTime { get; set; }
        public string errorMsg { get; set; }
        public string errorURL { get; set; }

        public virtual User User1 { get; set; }
    }
}