//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        public int ID { get; set; }
        public int partnerSiteID { get; set; }
        public string value { get; set; }
        public int posHorizontal { get; set; }
        public Nullable<int> posVertical { get; set; }
        public string text { get; set; }
        public Nullable<bool> IsDropMaster { get; set; }

        public int Index { get; set; }

        public virtual PartnerSite PartnerSite { get; set; }
    }
}
