//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CityAccessEntities : DbContext
    {
        public CityAccessEntities()
            : base("name=CityAccessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agreement> Agreements { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<commissionType> commissionTypes { get; set; }
        public virtual DbSet<Partner> Partners { get; set; }
        public virtual DbSet<serviceType> serviceTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<ServiceImage> ServiceImages { get; set; }
        public virtual DbSet<PartnerLogo> PartnerLogoes { get; set; }
        public virtual DbSet<RequestLog> RequestLogs { get; set; }
        public virtual DbSet<AgreementLog> AgreementLogs { get; set; }
        public virtual DbSet<DynamicField> DynamicFields { get; set; }
        public virtual DbSet<DynamicFieldAlternative> DynamicFieldAlternatives { get; set; }
        public virtual DbSet<DynamicFieldAlternativeMl> DynamicFieldAlternativeMls { get; set; }
        public virtual DbSet<DynamicFieldMl> DynamicFieldMls { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventState> EventStates { get; set; }
        public virtual DbSet<UserLog> UserLogs { get; set; }
        public virtual DbSet<Binary> Binarys { get; set; }
        public virtual DbSet<FontStyle> FontStyles { get; set; }
        public virtual DbSet<Link> Links { get; set; }
        public virtual DbSet<PartnerSite> PartnerSites { get; set; }
        public virtual DbSet<Style> Styles { get; set; }
        public virtual DbSet<StateTransition> StateTransitions { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
