//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CityAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Partner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partner()
        {
            this.Agreements = new HashSet<Agreement>();
            this.Users = new HashSet<User>();
            this.Services = new HashSet<Service>();
            this.PartnerLogoes = new HashSet<PartnerLogo>();
        }

        public int ID { get; set; }

        [Required(ErrorMessage = "Mandatory Field.")]
        [DisplayName("Trade name")]
        public string tradeName { get; set; }

        [Required(ErrorMessage = "Mandatory Field.")]
        [DisplayName("Notification e-mail")]
        public string email { get; set; }

        [Required(ErrorMessage = "Mandatory Field.")]
        [DisplayName("Description")]
        [DataType(DataType.MultilineText)]
        public string description { get; set; }

        [Required(ErrorMessage = "Mandatory Field.")]
        [DisplayName("VAT number")]
        public string fiscalID { get; set; }

        [Required(ErrorMessage = "Mandatory Field.")]
        [DisplayName("Country")]
        public string countryID { get; set; }

        [Required(ErrorMessage = "Mandatory Field.")]
        [DisplayName("Invoice name")]
        public string invoiceName { get; set; }

        [Required(ErrorMessage = "Mandatory Field.")]
        [DisplayName("Invoice address")]
        public string invoiceAddress { get; set; }

        [Required(ErrorMessage = "Mandatory Field.")]
        public Nullable<bool> isAgent { get; set; }

        [Required(ErrorMessage = "Mandatory Field.")]
        public Nullable<bool> isOperator { get; set; }

        [Required(ErrorMessage = "Mandatory Field.")]
        public bool isActive { get; set; }

        [Required(ErrorMessage = "Mandatory Field.")]
        public Nullable<bool> isPublic { get; set; }

        [Required(ErrorMessage = "Mandatory Field.")]
        [DisplayName("Contact person")]
        public string ContactPerson { get; set; }

        [Required(ErrorMessage = "Mandatory Field.")]
        [DisplayName("Contact phone")]
        public string ContactPhone { get; set; }

        [Required(ErrorMessage = "Mandatory Field.")]
        [DisplayName("Contact email")]
        public string ContactEmail { get; set; }

        [DisplayName("Logo")]
        public HttpPostedFileBase file { get; set; }

        public Nullable<int> invitedby { get; set; }

        public Nullable<bool> FromUser { get; set; }

        public Nullable<bool> isTest { get; set; }

        public Nullable<System.Guid> IcalLink { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agreement> Agreements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerLogo> PartnerLogoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerSite> PartnerSites { get; set; }
    }
}
