//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ServiceImage
    {
        public int ID { get; set; }
        public Nullable<int> serviceID { get; set; }
        [DisplayName("Image")]
        [MaxLength(100000)]
        public byte[] Image { get; set; }
        public Nullable<int> sequenceNR { get; set; }

        public virtual Service Service { get; set; }
    }
}
