//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Style
    {
        public int ID { get; set; }
        public int partnerSiteID { get; set; }
        public string BackgroundColor { get; set; }
        public string FontColor { get; set; }
        public Nullable<bool> MenuPosition { get; set; }
        public Nullable<bool> LogoPosition { get; set; }

        public string Font { get; set; }
    
        public virtual PartnerSite PartnerSite { get; set; }
    }
}
