//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserLog
    {
        public int ID { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = @"{0:dd/MM/yyyy}")]
        public System.DateTime Date { get; set; }
        public string Time { get; set; }
        public int editorID { get; set; }
        public int userID { get; set; }
        public string notes { get; set; }

        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
