//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Requests = new HashSet<Request>();
            this.RequestLogs = new HashSet<RequestLog>();
            this.AgreementLogs = new HashSet<AgreementLog>();
            this.ErrorLogs = new HashSet<ErrorLog>();
            this.Requests1 = new HashSet<Request>();
            this.UserLogs = new HashSet<UserLog>();
            this.UserLogs1 = new HashSet<UserLog>();
        }

        public int ID { get; set; }

        [DisplayName("Username")]
        [Required(ErrorMessage = "Mandatory Field.")]
        public string username { get; set; }

        [Required(ErrorMessage = "Mandatory Field.")]
        [DisplayName("Full name")]
        public string fullName { get; set; }


        [DisplayName("Password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Mandatory Field.")]
        public string password { get; set; }

        [Required(ErrorMessage = "Mandatory Field.")]
        [EmailAddress]
        [DisplayName("E-mail")]
        public string email { get; set; }

        //[Required(ErrorMessage = "Mandatory Field.")]
        [DisplayName("Phone")]
        public string phone { get; set; }

        [DisplayName("Last login")]
        public Nullable<System.DateTime> lastLoginDate { get; set; }

        [DisplayName("Partner")]
        public int partnerId { get; set; }

        [DisplayName("Is active")]
        public Nullable<bool> isActive { get; set; }

        public Nullable<bool> emailConfirmed { get; set; }


        public virtual Partner Partner { get; set; }

        public string LoginErrorMessage { get; set; }
        public string RegisterErrorMessage { get; set; }


        [DisplayName("Old password")]
        [DataType(DataType.Password)]
        public string Oldpassword { get; set; }


        [DisplayName("Confirm password")]
        [DataType(DataType.Password)]
        [Compare("password", ErrorMessage = "Confirm password doesn't match. Type again please.")]
        public string passwordConfirm { get; set; }

        [DisplayName("Is admin?")]
        public Nullable<bool> isAdmin { get; set; }

        public string EncodedUserId { get; set; }
        public string EncodedPartnerId { get; set; }


        public Nullable<System.Guid> UserIcalLink { get; set; }
    

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestLog> RequestLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgreementLog> AgreementLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ErrorLog> ErrorLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLog> UserLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLog> UserLogs1 { get; set; }
    }
}
